### ISSUE TITLE
Setup for inspecting somatic variants

### ISSUE THREAD

**Issue by mvdbeek** [MarWoes/viper#2]
I really like the current functionality, but it would be great if you could include a way to inspect multiple samples (e.g tumor/normal) at the same time for somatic variant calling.

**Comment by MarWoes** [comment]
That seems like a nice idea, I think allowing a .txt file containing tumor/normal relations would probably be the easiest way to implement this. I'll have a look at it!

**Comment by mvdbeek** [comment]
That would be fantastic, thanks a lot!

**Comment by MarWoes** [comment]
Implemented in v1.0.2. You may now specify a partner file which might look like this:
```
T1,C1
T2,C2
```
The tutorial page was also updated to show this feature. At the moment, pairs are not displayed simultaneously (did not work too well with window sizes) but displayed in a radio button list to choose the currently displayed sample.

**Comment by mvdbeek** [comment]
Thanks so much, that's awesome!
